### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by rlorigro** [tresoldi/dafsa#14]
Hi, I tried to create a dafsa object from the output of dafsa:

```
from dafsa import DAFSA


def main():
    lines = [
        "+-- #5: n(#6/2:<p>/2) [('p', 6)]",
        "+-- #6: F(#3/2:<s>/1) [('s', 3)]",
        "+-- #8: n(#3/1:<p>/1) [('p', 3)]"
    ]

    d = DAFSA(lines, condense=True)

    d.write_figure("d2.png")


if __name__ == "__main__":
    main()
```

And the program crashes, unfortunately. 
```
Traceback (most recent call last):
  File "test_dafsa.py", line 17, in <module>
    main()
  File "test_dafsa.py", line 11, in main
    d = DAFSA(lines, condense=True)
  File "/home/ryan/code/tokenizer/venv/lib/python3.8/site-packages/dafsa/dafsa.py", line 461, in __init__
    self.condense()
  File "/home/ryan/code/tokenizer/venv/lib/python3.8/site-packages/dafsa/dafsa.py", line 610, in condense
    if self._joining_round() == 0:
  File "/home/ryan/code/tokenizer/venv/lib/python3.8/site-packages/dafsa/dafsa.py", line 655, in _joining_round
    edge_info = [edge for edge in edges if edge["target"] == node_id][0]
IndexError: list index out of range

```

Is there a simple fix for this? It works properly when condense=False

**Comment by tresoldi** [comment]
Hi, thanks for the report! No idea right now, unfortunately I have not touched `dafsa` in a while, I will need to check.

Just one question, this is using the latest released version of the code currently in the `main` branch?

**Comment by rlorigro** [comment]
Hi, yes this is v1.0 from PyPI. One thing I noticed is that if you append the strings with unique prefixes (e.g. 'a','b','c') then it doesn't crash. I think it's something in the initialization. 

But on the other hand, when I look at the output, it doesn't look very condensed:
![image](https://user-images.githubusercontent.com/28764332/224371304-78e0d8c7-842d-4598-9afa-d0fc165c0430.png)
